#!/bin/bash
case $1 in
  'composer')
    docker compose exec php composer ${*:2}
  ;;
  'mm')
    docker compose exec php bin/console make:migration ${*:2}
  ;;
  'mg')
    docker compose exec php bin/console doctrine:migrations:migrate ${*:2}
  ;;
  'cc')
    docker-compose exec php bin/console cache:clear ${*:2}
  ;;
  'seed')
    docker compose exec php bin/console hautelook:fixtures:load
  ;;
  'test')
    docker compose exec php bin/phpunit ${*:2}
  ;;
  *)
    echo "docker compose exec php bin/console ${*:1}"
    docker compose exec php bin/console ${*:1}
  ;;
  'help')
echo <<< HELP
Usage:
  make:migration
  migrate
HELP
  ;;
esac
exit 0
