#!/bin/bash
case $1 in
  *)
    echo "docker compose exec php bin/console ${*:1}"
    docker compose exec php bin/console ${*:1}
  ;;
  'help')
echo <<< HELP
Usage:
  make:migration
  migrate
HELP
  ;;
esac
exit 0
